### ISSUE TITLE
Testing to Capture Multiple UIDs Writing to File System

### ISSUE THREAD

**Issue by jrhee12** [IBM/k8s-storage-tests#9]
**Main Issue**: If two processes with different non-root UIDs write to an EFS mount, the file ownership of one of the UIDs doesn't get maintained. It will result in one UID always be recorded in the file system. This has been observed during the EFS CSI driver certification process for Db2. 

**Request**:  EFS CSI driver needs to support two userIDs writing to a file system. The request is to include a testing feature that tests for the ability to handle maintaining mulitple UIDs in this scenario.

**Comment by parthakom2** [comment]
it is captured in the test with this PR - https://github.com/IBM/k8s-storage-tests/pull/10
